CONNECT QLCONGTY/DOAN;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE OR REPLACE PROCEDURE CREATE_ALL_USER
AS
    CURSOR NV_CURSOR IS SELECT MANV FROM QLCONGTY.NHANVIEN;
    MANV NVARCHAR2(50);
BEGIN
    FOR REC IN NV_CURSOR
    LOOP
        MANV := REC.MANV;
        EXECUTE IMMEDIATE 'BEGIN CREATE_USER(''' || MANV || ''', ''DOAN''); END;';
    END LOOP;
END;
EXEC CREATE_ALL_USER;

CREATE ROLE NHANVIEN;
CREATE ROLE QLTRUCTIEP;
CREATE ROLE TRUONGPHONG;
CREATE ROLE TAICHINH;
CREATE ROLE NHANSU;
CREATE ROLE TRUONGDEAN;
CREATE ROLE BANGIAMDOC;
