CREATE OR REPLACE VIEW S_NHANVIEN AS
    SELECT * FROM QLCONGTY.NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER')
    UNION
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, NULL AS LUONG, NULL AS PHUCAP , VAITRO, MANQL, PHG FROM QLCONGTY.NHANVIEN
    WHERE MANQL = SYS_CONTEXT('USERENV', 'SESSION_USER')

--PHONGBAN
CREATE OR REPLACE FUNCTION QLCONGTY.MANAGEPHONGBAN(
    OBJ_SCHEMA IN VARCHAR2,
    OBJ_NAME IN VARCHAR2
)
RETURN VARCHAR2
AS
    IDEMP VARCHAR2(20);
BEGIN
    
    IDEMP := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF(IDEMP LIKE 'NS%') THEN RETURN '1=1';
    ELSE RETURN '0=1';
    END IF;
END;

CREATE OR REPLACE FUNCTION QLCONGTY.SELECTNHANVIEN(
    OBJ_SCHEMA IN VARCHAR2,
    OBJ_NAME IN VARCHAR2
)
RETURN VARCHAR2
AS
    IDEMP VARCHAR2(20);
BEGIN
    IDEMP := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF (IDEMP LIKE 'TC%') THEN RETURN '1=1';
    ELSIF (IDEMP LIKE 'QL%') THEN RETURN 'MANV = ''' || IDEMP || '''OR MANQL = ''' || IDEMP || '''';
    ELSE RETURN 'MANV = ''' || IDEMP || '''';
    END IF;
END;

CREATE OR REPLACE FUNCTION QLCONGTY.CHANGENHANVIEN(
    OBJ_SCHEMA IN VARCHAR2,
    OBJ_NAME IN VARCHAR2
)
RETURN VARCHAR2
AS
    IDEMP VARCHAR2(20);
    ROLEUSER NVARCHAR2(15);
BEGIN
    IDEMP := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF (IDEMP LIKE 'NS%') THEN RETURN 'LUONG IS NULL AND PHUCAP IS NULL';
    ELSE RETURN 'MANV = ''' || IDEMP || '''';
    END IF;
END;

CREATE OR REPLACE FUNCTION QLCONGTY.SELECTPHANCONG(
    OBJ_SCHEMA IN VARCHAR2,
    OBJ_NAME IN VARCHAR2
)
RETURN VARCHAR2
AS
    IDEMP CHAR(5);
BEGIN
    IDEMP := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF (IDEMP LIKE 'QL%') THEN RETURN 'MANV = ''' || IDEMP || '''OR MANV IN (SELECT MANV FROM QLCONGTY.NHANVIEN WHERE MANQL = ''' || IDEMP || ''')';
    --ELSE RETURN 'MANV = ''' || IDEMP || '''';
    END IF;
END;

